name: CI Notice

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      
      - uses: actions-cool/ci-notice@main
        with:
          ci: |
            yarn
            yarn run package
            yarn run docs:build
          notice-types: 'issue'
          issue-assignees: 'xrkffgg'
